version: 2

models:
  - name: stg_support_tickets
    columns:
      - name: ticket_id
        tests: [not_null, unique]
      - name: message_text
        tests: [not_null]
  - name: stg_ticket_enrichments
    columns:
      - name: ticket_id
        tests:
          - not_null
          - unique
      - name: sentiment
        tests:
          - accepted_values:
              values: ['positive', 'neutral', 'negative']
      - name: urgency
        tests:
          - accepted_values:
              values: ['low', 'medium', 'high', 'critical']
